#!/usr/bin/env python3
"""Audit the Learning English dictionary data generated by learning-english.html."""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HTML_PATH = ROOT / "learning-english.html"


def extract_inline_script(html: str) -> str:
    start = html.find("<script>")
    end = html.rfind("</script>")
    if start == -1 or end == -1 or end <= start:
        raise ValueError("Could not find inline learning script")
    return html[start + len("<script>") : end]


def run_node_audit(script: str) -> dict:
    harness = r"""
const element = () => ({
  addEventListener() {},
  appendChild() {},
  classList: { add() {}, remove() {}, toggle() {} },
  dataset: {},
  innerHTML: "",
  options: [],
  querySelector() { return null; },
  querySelectorAll() { return []; },
  scrollIntoView() {},
  setAttribute() {},
  textContent: "",
  value: "",
});
const storage = {};
const localStorage = {
  getItem(key) { return Object.prototype.hasOwnProperty.call(storage, key) ? storage[key] : null; },
  setItem(key, value) { storage[key] = String(value); },
  removeItem(key) { delete storage[key]; },
};
const document = {
  getElementById() { return element(); },
  querySelector() { return null; },
  querySelectorAll() { return []; },
};
const window = { localStorage, speechSynthesis: { cancel() {}, speak() {} } };
globalThis.localStorage = localStorage;
globalThis.document = document;
globalThis.window = window;
"""
    audit = r"""
const items = buildDictionaryItems();
const typeCounts = items.reduce((map, item) => {
  map[item.sourceType] = (map[item.sourceType] || 0) + 1;
  return map;
}, {});
const themeCounts = DICTIONARY_THEME_TOPICS.reduce((map, topic) => {
  map[topic.id] = items.filter((item) => item.theme === topic.id).length;
  return map;
}, {});
const vocabulary = getAllVocabulary();
const wordMetadataGaps = vocabulary.filter((item) => {
  const ipa = getVocabularyIpa(item);
  return !ipa || item.prefix === undefined || item.suffix === undefined || item.roots === undefined ||
    item.syllableType === undefined || item.vowelTeams === undefined || !item.theme;
}).map((item) => ({
  id: item.id,
  word: item.word,
  missing: [
    getVocabularyIpa(item) ? "" : "ipa",
    item.prefix === undefined ? "prefix" : "",
    item.suffix === undefined ? "suffix" : "",
    item.roots === undefined ? "roots" : "",
    item.syllableType === undefined ? "syllableType" : "",
    item.vowelTeams === undefined ? "vowelTeams" : "",
    item.theme ? "" : "theme",
  ].filter(Boolean),
}));
const requiredTypes = ["word", "sentence", "phrase", "dialogue-sentence"];
const missingTypes = requiredTypes.filter((type) => !typeCounts[type]);
console.log(JSON.stringify({
  ok: missingTypes.length === 0 && wordMetadataGaps.length === 0,
  totalItems: items.length,
  typeCounts,
  themeCounts,
  missingTypes,
  wordMetadataGaps,
}, null, 2));
"""
    with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False, encoding="utf-8") as handle:
      handle.write(harness)
      handle.write("\n")
      handle.write(script)
      handle.write("\n")
      handle.write(audit)
      node_path = handle.name

    try:
        result = subprocess.run(
            ["node", node_path],
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
        )
    finally:
        Path(node_path).unlink(missing_ok=True)

    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "node audit failed")
    return json.loads(result.stdout)


def main() -> int:
    html = HTML_PATH.read_text(encoding="utf-8")
    report = run_node_audit(extract_inline_script(html))
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except FileNotFoundError as exc:
        print(f"Missing runtime: {exc}", file=sys.stderr)
        raise SystemExit(2)
    except Exception as exc:
        print(f"Audit failed: {exc}", file=sys.stderr)
        raise SystemExit(2)
